steps:
- name: 'ubuntu' # Use a pre-built Docker image
  entrypoint: 'bash'
  args: ['-c', 'echo "Hello, Cloud Build!"']
build:
  service_account: "cicd-959@profound-matter-446906-r5.iam.gserviceaccount.com"
  logging:
    cloud_logging: CLOUD_LOGGING_ONLY
